# Generated by Django 5.2.10 on 2026-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareWig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Cliente"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Reçue"),
                            ("IN_PROGRESS", "En cours"),
                            ("READY", "Prête"),
                            ("DELIVERED", "Remise à la cliente"),
                            ("CANCELED", "Annulée"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Perruque en entretien",
                "verbose_name_plural": "Perruques en entretien",
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=20, unique=True, verbose_name="Clé"),
                ),
                (
                    "value",
                    models.PositiveIntegerField(default=0, verbose_name="Compteur"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Séquence",
                "verbose_name_plural": "Séquences",
            },
        ),
        migrations.CreateModel(
            name="WigProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_STOCK", "En stock"),
                            ("RESERVED", "Réservée"),
                            ("SOLD", "Vendue"),
                            ("RETOUCH", "Retouche"),
                            ("RETURNED", "Retour"),
                        ],
                        default="IN_STOCK",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Prix"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Perruque",
                "verbose_name_plural": "Perruques",
            },
        ),
    ]
