# Generated by Django 5.2.10 on 2026-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wigs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carewig",
            name="label_printed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Étiquette imprimée le"
            ),
        ),
        migrations.AddField(
            model_name="carewig",
            name="promised_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date promise"),
        ),
    ]
