# Generated by Django 5.2.10 on 2026-01-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom")),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="SKU"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("SALE", "Vente"), ("CONSUMABLE", "Consommable")],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock minimum"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantité")),
                (
                    "alert",
                    models.BooleanField(default=False, verbose_name="Alerte stock"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_level",
                        to="inventory.inventoryitem",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau de stock",
                "verbose_name_plural": "Niveaux de stock",
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(verbose_name="Quantité")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrée"),
                            ("OUT", "Sortie"),
                            ("ADJUST", "Ajustement"),
                            ("LOSS", "Perte"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Référence"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_moves",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="inventory.inventoryitem",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
            },
        ),
    ]
