# Generated by Django 4.2.15 on 2026-01-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCompletionRule",
            fields=[],
            options={
                "verbose_name": "Règle cours",
                "verbose_name_plural": "Règles cours",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.completionrule",),
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.module",),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[],
            options={
                "verbose_name": "Progression",
                "verbose_name_plural": "Progressions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.progress",),
        ),
        migrations.CreateModel(
            name="LessonResource",
            fields=[],
            options={
                "verbose_name": "Ressource",
                "verbose_name_plural": "Ressources",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.resource",),
        ),
        migrations.CreateModel(
            name="ModuleCompletionRule",
            fields=[],
            options={
                "verbose_name": "Règle module",
                "verbose_name_plural": "Règles module",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.completionrule",),
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[],
            options={
                "verbose_name": "Réponse quiz",
                "verbose_name_plural": "Réponses quiz",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.submissionanswer",),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[],
            options={
                "verbose_name": "Soumission quiz",
                "verbose_name_plural": "Soumissions quiz",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.submission",),
        ),
        migrations.CreateModel(
            name="QuizChoice",
            fields=[],
            options={
                "verbose_name": "Choix",
                "verbose_name_plural": "Choix",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.choice",),
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lms.question",),
        ),
    ]
