# Generated by Django 4.2.15 on 2026-01-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_progress_completion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="feedback",
            field=models.TextField(blank=True, verbose_name="Feedback"),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("REJECTED", "Rejeté"),
                    ("APPROVED", "Validé"),
                ],
                default="SUBMITTED",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
