# Generated by Django 4.2.15 on 2026-01-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_badge_assignment_criteria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("COURSE_COMPLETED", "Cours terminé"),
                    ("MODULE_COMPLETED", "Module terminé"),
                    ("QUIZ_SCORE", "Score quiz"),
                    ("KPI_TARGET", "Objectif KPI"),
                    ("ASSIGNMENT_APPROVED", "Devoir validé"),
                ],
                default="COURSE_COMPLETED",
                max_length=30,
                verbose_name="Règle",
            ),
        ),
    ]
