# Generated by Django 5.2.10 on 2026-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencerule",
            name="weekdays",
            field=models.CharField(
                blank=True,
                help_text="Numéros 0 (lundi) à 6 (dimanche) séparés par des virgules.",
                max_length=20,
                verbose_name="Jours de la semaine",
            ),
        ),
    ]
