# Generated by Django 5.2.10 on 2026-01-13 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_recurrencerule_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurrencerule",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Créé le"
            ),
        ),
        migrations.AddField(
            model_name="recurrencerule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
    ]
