# Generated by Django 5.2.10 on 2026-01-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyversereceipt",
            name="receipt_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=120,
                verbose_name="Identifiant",
            ),
        ),
    ]
