# Generated by Django 5.2.10 on 2026-01-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_reference",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Référence manuelle"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_link",
                        to="operations.activity",
                        verbose_name="Activité",
                    ),
                ),
                (
                    "loyverse_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_links",
                        to="integrations.loyversereceipt",
                        verbose_name="Reçu Loyverse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de paiement",
                "verbose_name_plural": "Liens de paiement",
            },
        ),
    ]
