# Generated by Django 4.2.15 on 2026-01-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_service_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
    ]
