# Generated by Django 4.2.15 on 2026-01-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_service_options"),
        ("operations", "0005_update_category_images"),
    ]

    operations = []
