# Generated by Django 4.2.15 on 2026-01-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_merge_20260120_0521"),
        ("operations", "0006_sync_service_catalog"),
    ]

    operations = []
