# Generated by Django 5.2.10 on 2026-01-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idée"),
                            ("BRIEF", "Brief"),
                            ("IN_CREATION", "En création"),
                            ("TO_VALIDATE", "À valider"),
                            ("APPROVED", "Validé"),
                            ("SCHEDULED", "Programmé"),
                            ("PUBLISHED", "Publié"),
                            ("METRICS_RECORDED", "Résultats saisis"),
                            ("REJECTED", "Refusé"),
                        ],
                        default="IDEA",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_content_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenu",
                "verbose_name_plural": "Contenus",
            },
        ),
        migrations.CreateModel(
            name="ContentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Commentaire")),
                ("approved", models.BooleanField(default=False, verbose_name="Validé")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="content.contentitem",
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation de contenu",
                "verbose_name_plural": "Validations de contenu",
            },
        ),
        migrations.CreateModel(
            name="ContentMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("likes", models.PositiveIntegerField(default=0, verbose_name="Likes")),
                (
                    "comments",
                    models.PositiveIntegerField(default=0, verbose_name="Commentaires"),
                ),
                (
                    "shares",
                    models.PositiveIntegerField(default=0, verbose_name="Partages"),
                ),
                (
                    "saves",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Enregistrements"
                    ),
                ),
                (
                    "reach",
                    models.PositiveIntegerField(default=0, verbose_name="Portée"),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clics"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "content_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="content.contentitem",
                        verbose_name="Contenu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Métrique de contenu",
                "verbose_name_plural": "Métriques de contenu",
            },
        ),
    ]
