# Generated by Django 5.2.10 on 2026-01-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentitem",
            name="platform",
            field=models.CharField(
                choices=[
                    ("INSTAGRAM", "Instagram"),
                    ("TIKTOK", "TikTok"),
                    ("FACEBOOK", "Facebook"),
                    ("WHATSAPP", "WhatsApp"),
                    ("YOUTUBE", "YouTube"),
                    ("OTHER", "Autre"),
                ],
                default="INSTAGRAM",
                max_length=20,
                verbose_name="Plateforme",
            ),
        ),
    ]
