# Generated by Django 4.2.15 on 2026-01-20 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0002_seed_training_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Quiz",
                "verbose_name_plural": "Quiz",
            },
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="completion_mode",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manuel"),
                    ("CHECKLIST_ONLY", "Checklist seule"),
                    ("QUIZ_ONLY", "Quiz seul"),
                    ("CHECKLIST_AND_QUIZ", "Checklist + quiz"),
                    ("CHECKLIST_QUIZ_AND_SUBMISSION", "Checklist + quiz + soumission"),
                ],
                default="MANUAL",
                max_length=40,
                verbose_name="Mode de complétion",
            ),
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="content_html",
            field=models.TextField(blank=True, verbose_name="Contenu (HTML)"),
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="content_md",
            field=models.TextField(blank=True, verbose_name="Contenu (Markdown)"),
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="estimated_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Temps estimé (min)"
            ),
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="passing_score",
            field=models.PositiveIntegerField(default=70, verbose_name="Score requis"),
        ),
        migrations.AddField(
            model_name="traininglesson",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Vidéo (URL)"),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="quiz_best_score",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Meilleur score quiz (%)"
            ),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="quiz_passed",
            field=models.BooleanField(default=False, verbose_name="Quiz validé"),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="submission_done",
            field=models.BooleanField(default=False, verbose_name="Soumission faite"),
        ),
        migrations.AddField(
            model_name="trainingprogress",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Vu le"),
        ),
        migrations.CreateModel(
            name="TrainingSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_md", models.TextField(verbose_name="Consigne")),
                ("submission_text", models.TextField(verbose_name="Soumission")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Soumis le"),
                ),
                (
                    "score_percent",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Score %"
                    ),
                ),
                (
                    "reviewer_comment",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUBMITTED", "Soumis"), ("REVIEWED", "Corrigé")],
                        default="SUBMITTED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="training.traininglesson",
                        verbose_name="Module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soumission",
                "verbose_name_plural": "Soumissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingQuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Démarré le"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soumis le"
                    ),
                ),
                (
                    "score_percent",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Score %"
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Réussi")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="training.trainingquiz",
                        verbose_name="Quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentative quiz",
                "verbose_name_plural": "Tentatives quiz",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="trainingquiz",
            name="lesson",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz",
                to="training.traininglesson",
                verbose_name="Module",
            ),
        ),
        migrations.CreateModel(
            name="TrainingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Question")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "QCM"),
                            ("TRUE_FALSE", "Vrai/Faux"),
                            ("OPEN", "Ouverte"),
                        ],
                        default="MCQ",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Ordre")),
                (
                    "points",
                    models.PositiveIntegerField(default=1, verbose_name="Points"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explication"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="training.trainingquiz",
                        verbose_name="Quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["quiz", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.TextField(verbose_name="Choix")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Correct"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Ordre")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="training.trainingquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choix",
                "verbose_name_plural": "Choix",
                "ordering": ["question", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(blank=True, verbose_name="Réponse libre"),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="Correct"),
                ),
                (
                    "points_awarded",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Points attribués"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="training.trainingquizattempt",
                        verbose_name="Tentative",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="training.trainingquestion",
                        verbose_name="Question",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="selected_answers",
                        to="training.trainingchoice",
                        verbose_name="Choix",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse quiz",
                "verbose_name_plural": "Réponses quiz",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
