# Generated by Django 4.2.15 on 2026-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_trainingquiz_traininglesson_completion_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglesson",
            name="case_prompt_md",
            field=models.TextField(blank=True, verbose_name="Mini-cas (consigne)"),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="Slug"
            ),
        ),
    ]
