# Generated by Django 4.2.15 on 2026-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_traininglesson_case_prompt_md_trainingprogram_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglessonresource",
            name="content_md",
            field=models.TextField(blank=True, verbose_name="Contenu (Markdown)"),
        ),
    ]
