# Generated by Django 4.2.15 on 2026-01-20 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("training", "0005_traininglessonresource_content_md"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingStudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("SYNTHESIS", "Fiche de synthèse"),
                            ("PRACTICAL_GUIDE", "Guide pratique"),
                            ("REVISION", "Guide de révision"),
                        ],
                        default="SYNTHESIS",
                        max_length=30,
                        verbose_name="Type de support",
                    ),
                ),
                ("content_md", models.TextField(verbose_name="Contenu (Markdown)")),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Indispensable"),
                ),
                (
                    "recommended_before_quiz",
                    models.BooleanField(
                        default=False, verbose_name="À étudier avant le quiz"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="training.traininglesson",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support d'étude",
                "verbose_name_plural": "Supports d'étude",
                "ordering": ["lesson", "support_type", "title", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingStudyMaterialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Consulté le"),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_items",
                        to="training.trainingstudymaterial",
                        verbose_name="Support",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_study_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression support",
                "verbose_name_plural": "Progressions supports",
                "unique_together": {("material", "user")},
            },
        ),
    ]
