# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week1_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "Cartographie des services Floxy Made",
            "supports": [
                {
                    "title": "Fiche de synthèse – Cartographie des services Floxy Made",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Cartographie des services Floxy Made\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les 5 pôles Floxy Made : coiffure, perruques, make-up, onglerie, soins.\n"
                        "- Chaque service doit répondre à un **besoin client précis**.\n"
                        "- On priorise les services **forte demande + bonne marge**.\n\n"
                        "## Définitions simples\n"
                        "- **Service phare** : prestation la plus demandée ou la plus rentable.\n"
                        "- **Valeur client** : ce que la cliente gagne (résultat, temps, confiance).\n"
                        "- **Argument de valeur** : phrase courte qui vend le bénéfice.\n\n"
                        "## Règles importantes\n"
                        "- 1 service = 1 besoin client clair.\n"
                        "- 3 arguments maximum par prestation.\n"
                        "- Chaque service doit être rattaché à un secteur précis.\n\n"
                        "## Erreurs à éviter\n"
                        "- Lister des services sans marge ou sans demande.\n"
                        "- Mélanger perruques/onglerie dans une même offre.\n"
                        "- Oublier les upsells (soin, entretien, accessoire).\n"
                    ),
                },
                {
                    "title": "Guide pratique – Cartographie des services Floxy Made",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Cartographie des services Floxy Made\n\n"
                        "## Comment appliquer concrètement au salon\n"
                        "1. Lister tous les services par secteur (tableau simple).\n"
                        "2. Ajouter **prix**, **durée**, **besoin client**.\n"
                        "3. Attribuer un niveau de marge : Haute / Moyenne / Faible.\n"
                        "4. Sélectionner 3 services phares par secteur.\n"
                        "5. Valider avec la direction puis diffuser à l’équipe.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Créer une **fiche service** par prestation phare.\n"
                        "- Construire une **matrice valeur client** (besoin → bénéfice).\n"
                        "- Préparer un argumentaire court pour chaque service phare.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure** : Lissage brésilien → gain de temps + cheveux disciplinés.\n"
                        "- **Perruques** : Pose lace frontal → naturel + confort.\n"
                        "- **Make-up** : Maquillage événement → tenue longue + photos réussies.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Cartographie des services Floxy Made",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Cartographie des services Floxy Made\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 5 pôles Floxy Made et leurs services phares.\n"
                        "- La notion de **valeur client** et d’**argument de valeur**.\n"
                        "- Les livrables : tableau par secteur + arguments de valeur.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q2** : objectif du module + pôles Floxy Made.\n"
                        "- **Q3–Q4** : service phare + valeur client.\n"
                        "- **Q5–Q8** : exemples par secteur (coiffure, perruques, make-up, onglerie, soins).\n"
                        "- **Q9–Q10** : erreurs fréquentes et corrections.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Réaliser une cartographie simple avec 3 services phares.\n"
                        "- Fournir un argumentaire clair par prestation.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Parcours client standardisé",
            "supports": [
                {
                    "title": "Fiche de synthèse – Parcours client standardisé",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Parcours client standardisé\n\n"
                        "## Concepts clés à retenir\n"
                        "- 5 étapes : accueil → diagnostic → prestation → paiement → suivi.\n"
                        "- Un parcours standard augmente la satisfaction et les avis positifs.\n"
                        "- Chaque étape a un script simple et une checklist.\n\n"
                        "## Définitions simples\n"
                        "- **Diagnostic** : questions courtes pour comprendre besoin, budget, délai.\n"
                        "- **Script** : phrases prêtes à l’emploi pour l’équipe.\n"
                        "- **Suivi post-prestation** : message J+1 / J+7 / J+21.\n\n"
                        "## Règles importantes\n"
                        "- L’accueil doit être chaleureux et rapide (<2 min).\n"
                        "- Le diagnostic est obligatoire avant toute prestation.\n"
                        "- Le paiement se fait avec rappel du prochain RDV.\n\n"
                        "## Erreurs à éviter\n"
                        "- Sauter le diagnostic pour gagner du temps.\n"
                        "- Encaisser sans proposer un suivi ou un prochain RDV.\n"
                        "- Laisser la cliente partir sans message de remerciement.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Parcours client standardisé",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Parcours client standardisé\n\n"
                        "## Application concrète au salon\n"
                        "1. Préparer un **script d’accueil** (1 phrase de bienvenue + 1 question).\n"
                        "2. Utiliser un mini-diagnostic : type de service, budget, résultat attendu.\n"
                        "3. Appliquer la prestation + valider le résultat avec la cliente.\n"
                        "4. Encaisser et proposer un prochain rendez-vous.\n"
                        "5. Envoyer un message WhatsApp de suivi après 24h.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Mettre une checklist imprimée à l’accueil.\n"
                        "- Former l’équipe par simulation (jeu de rôle).\n"
                        "- Évaluer 3 clientes réelles et ajuster le script.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Perruques** : vérifier taille + confort + entretien recommandé.\n"
                        "- **Coiffure** : diagnostic rapide sur l’état du cuir chevelu.\n"
                        "- **Onglerie** : vérifier allergies + type de pose souhaité.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Parcours client standardisé",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Parcours client standardisé\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 5 étapes et leur ordre exact.\n"
                        "- Les scripts clés : accueil, diagnostic, paiement, suivi.\n"
                        "- Les livrables : checklist accueil + diagnostic, script paiement + suivi.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : étapes du parcours et rôle du diagnostic.\n"
                        "- **Q4–Q6** : scripts et exemples concrets.\n"
                        "- **Q7–Q10** : erreurs fréquentes et conséquences.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Concevoir un parcours complet pour un service choisi.\n"
                        "- Proposer un script d’accueil + un message de suivi.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Organisation quotidienne & standards",
            "supports": [
                {
                    "title": "Fiche de synthèse – Organisation quotidienne & standards",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Organisation quotidienne & standards\n\n"
                        "## Concepts clés à retenir\n"
                        "- La journée est pilotée par **planning + hygiène + caisse**.\n"
                        "- Les standards évitent les oublis et les pertes.\n"
                        "- La routine se répète chaque jour pour l’autonomie.\n\n"
                        "## Définitions simples\n"
                        "- **Routine ouverture/fermeture** : liste d’actions obligatoires.\n"
                        "- **Standards hygiène** : règles fixes appliquées à toutes les prestations.\n"
                        "- **Coordination prestataires** : qui fait quoi, à quel moment.\n\n"
                        "## Règles importantes\n"
                        "- Planning affiché et validé la veille.\n"
                        "- Check hygiène avant le premier rendez-vous.\n"
                        "- Caisse comptée et reportée en fin de journée.\n\n"
                        "## Erreurs à éviter\n"
                        "- Démarrer sans briefing.\n"
                        "- Oublier les contrôles hygiène.\n"
                        "- Fermer sans vérification de la caisse.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Organisation quotidienne & standards",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Organisation quotidienne & standards\n\n"
                        "## Application concrète au salon\n"
                        "1. Préparer un **planning hebdomadaire** avec pics d’activité.\n"
                        "2. Établir une **routine d’ouverture** (propreté, outils, caisse).\n"
                        "3. Lancer un briefing rapide chaque matin (10 min).\n"
                        "4. Noter les ventes et incidents en fin de journée.\n"
                        "5. Diffuser la routine de fermeture à toute l’équipe.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Créer un tableau “Qui fait quoi” par créneau horaire.\n"
                        "- Afficher la checklist hygiène près des postes.\n"
                        "- Organiser un point quotidien sur la caisse.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure** : vérifier les postes lissage avant 10h.\n"
                        "- **Perruques** : désinfecter outils entre deux clientes.\n"
                        "- **Soins** : préparer les cabines et les serviettes propres.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Organisation quotidienne & standards",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Organisation quotidienne & standards\n\n"
                        "## À maîtriser absolument\n"
                        "- Le rôle du planning quotidien/hebdomadaire.\n"
                        "- La routine hygiène et la routine caisse.\n"
                        "- Les livrables : routine ouverture/fermeture + planning type.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : objectifs et éléments clés de la routine.\n"
                        "- **Q4–Q6** : standards hygiène + caisse.\n"
                        "- **Q7–Q10** : erreurs fréquentes et risques.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire une journée type et préciser les contrôles.\n"
                        "- Proposer une routine de suivi quotidienne.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Scripts d'accueil & checklists opérationnelles",
            "supports": [
                {
                    "title": "Fiche de synthèse – Scripts d'accueil & checklists opérationnelles",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Scripts d'accueil & checklists opérationnelles\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les scripts garantissent une expérience client homogène.\n"
                        "- Les checklists évitent les oublis et sécurisent la qualité.\n"
                        "- Chaque service clé doit avoir son propre script + checklist.\n\n"
                        "## Définitions simples\n"
                        "- **Script d’accueil** : phrase standard pour démarrer la relation.\n"
                        "- **Checklist opérationnelle** : liste d’étapes à cocher.\n"
                        "- **Qualité standardisée** : même niveau de service pour toutes.\n\n"
                        "## Règles importantes\n"
                        "- Un script doit tenir en 4 à 6 phrases maximum.\n"
                        "- La checklist est adaptée par service (coiffure, perruques, etc.).\n"
                        "- L’équipe valide le script avant diffusion.\n\n"
                        "## Erreurs à éviter\n"
                        "- Utiliser un script trop long ou trop technique.\n"
                        "- Copier un script sans l’adapter au secteur.\n"
                        "- Ne pas contrôler l’application des checklists.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Scripts d'accueil & checklists opérationnelles",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Scripts d'accueil & checklists opérationnelles\n\n"
                        "## Application concrète au salon\n"
                        "1. Choisir 3 services phares (ex: lissage, pose perruque, make-up).\n"
                        "2. Rédiger un script court pour chaque service.\n"
                        "3. Créer une checklist avec 5 à 7 étapes maximum.\n"
                        "4. Tester les scripts sur 3 clientes réelles.\n"
                        "5. Ajuster puis formaliser pour toute l’équipe.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Lister les actions indispensables par prestation.\n"
                        "- Ajouter 1 étape de validation finale (satisfaction cliente).\n"
                        "- Distribuer la checklist imprimée aux postes.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Perruques** : accueil + diagnostic + pose + conseils entretien.\n"
                        "- **Onglerie** : choix modèle + préparation + pose + finition.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Scripts d'accueil & checklists opérationnelles",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Scripts d'accueil & checklists opérationnelles\n\n"
                        "## À maîtriser absolument\n"
                        "- Pourquoi un script court est plus efficace.\n"
                        "- Comment structurer une checklist par service.\n"
                        "- Les livrables : scripts prêts + checklists par prestation.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : objectifs des scripts et checklists.\n"
                        "- **Q4–Q6** : étapes clés et exemples.\n"
                        "- **Q7–Q10** : erreurs fréquentes et corrections.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer un script d’accueil complet.\n"
                        "- Construire une checklist opérationnelle concrète.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week1_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – Cartographie des services Floxy Made",
            "Guide pratique – Cartographie des services Floxy Made",
            "Guide de révision – Cartographie des services Floxy Made",
            "Fiche de synthèse – Parcours client standardisé",
            "Guide pratique – Parcours client standardisé",
            "Guide de révision – Parcours client standardisé",
            "Fiche de synthèse – Organisation quotidienne & standards",
            "Guide pratique – Organisation quotidienne & standards",
            "Guide de révision – Organisation quotidienne & standards",
            "Fiche de synthèse – Scripts d'accueil & checklists opérationnelles",
            "Guide pratique – Scripts d'accueil & checklists opérationnelles",
            "Guide de révision – Scripts d'accueil & checklists opérationnelles",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_trainingstudymaterial_trainingstudymaterialprogress"),
    ]

    operations = [
        migrations.RunPython(seed_week1_study_materials, unseed_week1_study_materials),
    ]
