# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week2_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "CRM : fiches clientes et segmentation",
            "supports": [
                {
                    "title": "Fiche de synthèse – CRM : fiches clientes et segmentation",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – CRM : fiches clientes et segmentation\n\n"
                        "## Concepts clés à retenir\n"
                        "- Une fiche cliente complète = meilleur suivi + ventes répétées.\n"
                        "- La segmentation permet d’envoyer le bon message au bon moment.\n"
                        "- 3 segments minimum : VIP, régulières, dormantes.\n\n"
                        "## Définitions simples\n"
                        "- **CRM** : outil qui garde l’historique des clientes et des actions.\n"
                        "- **Segment** : groupe de clientes avec un comportement similaire.\n"
                        "- **Dormante** : cliente sans visite depuis 60–90 jours.\n\n"
                        "## Règles importantes\n"
                        "- Chaque prestation doit mettre à jour la fiche cliente.\n"
                        "- Un segment = une action claire (relance, offre, fidélité).\n"
                        "- Les données clés = téléphone, secteur, dernier service, fréquence.\n\n"
                        "## Erreurs à éviter\n"
                        "- Laisser des fiches vides ou incomplètes.\n"
                        "- Tout envoyer à tout le monde (pas de segmentation).\n"
                        "- Ne pas suivre l’historique des préférences.\n"
                    ),
                },
                {
                    "title": "Guide pratique – CRM : fiches clientes et segmentation",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – CRM : fiches clientes et segmentation\n\n"
                        "## Application concrète au salon\n"
                        "1. Créer un modèle de fiche cliente (papier ou digital).\n"
                        "2. Renseigner les champs obligatoires après chaque prestation.\n"
                        "3. Créer 3 segments : VIP, régulières, dormantes.\n"
                        "4. Associer une action à chaque segment (relance, remerciement, offre).\n"
                        "5. Mettre à jour la fiche à chaque interaction WhatsApp.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Former l’équipe à la prise d’infos en 2 minutes.\n"
                        "- Ajouter un tag “service préféré”.\n"
                        "- Contrôler 10 fiches par semaine pour vérifier la qualité.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **VIP** : proposez un soin premium offert après 3 visites.\n"
                        "- **Dormante** : message “On vous manque ?” + réduction ciblée.\n"
                    ),
                },
                {
                    "title": "Guide de révision – CRM : fiches clientes et segmentation",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – CRM : fiches clientes et segmentation\n\n"
                        "## À maîtriser absolument\n"
                        "- Champs essentiels d’une fiche cliente.\n"
                        "- Les 3 segments minimum et leurs objectifs.\n"
                        "- Pourquoi la segmentation augmente les retours.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q2** : définition CRM + fiche cliente.\n"
                        "- **Q3–Q5** : segments VIP/régulières/dormantes.\n"
                        "- **Q6–Q8** : actions adaptées par segment.\n"
                        "- **Q9–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Créer une fiche cliente complète.\n"
                        "- Proposer un plan d’action par segment.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Suivi post-prestation J+1/J+7/J+21",
            "supports": [
                {
                    "title": "Fiche de synthèse – Suivi post-prestation J+1/J+7/J+21",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Suivi post-prestation J+1/J+7/J+21\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le suivi augmente la fidélité et réduit les réclamations.\n"
                        "- 3 temps clés : J+1 (satisfaction), J+7 (conseil), J+21 (relance).\n"
                        "- Un message court, personnalisé et orienté service.\n\n"
                        "## Définitions simples\n"
                        "- **J+1** : vérification de la satisfaction et du confort.\n"
                        "- **J+7** : conseil d’entretien ou produit complémentaire.\n"
                        "- **J+21** : proposition de rendez-vous ou offre ciblée.\n\n"
                        "## Règles importantes\n"
                        "- Le message doit mentionner le service réalisé.\n"
                        "- Un seul objectif par message (satisfaction, conseil, RDV).\n"
                        "- Toujours proposer un canal de réponse simple (WhatsApp).\n\n"
                        "## Erreurs à éviter\n"
                        "- Copier-coller un message générique.\n"
                        "- Envoyer trop de promotions sans lien avec la prestation.\n"
                        "- Oublier les clientes insatisfaites.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Suivi post-prestation J+1/J+7/J+21",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Suivi post-prestation J+1/J+7/J+21\n\n"
                        "## Application concrète au salon\n"
                        "1. Après chaque prestation, programmer 3 relances automatiques.\n"
                        "2. Utiliser un script court (20–30 mots max).\n"
                        "3. Suivre les réponses dans le CRM.\n"
                        "4. Noter les retours clients et ajuster le service.\n\n"
                        "## Étapes opérationnelles\n"
                        "- J+1 : “Bonjour [Prénom], comment se passe votre [service] ?”\n"
                        "- J+7 : “Petit conseil entretien + produit conseillé.”\n"
                        "- J+21 : “Souhaitez-vous réserver votre prochain RDV ?”\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Perruques** : rappel entretien + lavage recommandé.\n"
                        "- **Onglerie** : conseil soin cuticules + rappel RDV.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Suivi post-prestation J+1/J+7/J+21",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Suivi post-prestation J+1/J+7/J+21\n\n"
                        "## À maîtriser absolument\n"
                        "- Objectif de chaque relance (J+1/J+7/J+21).\n"
                        "- Structure d’un message de suivi.\n"
                        "- Impact direct sur la fidélité.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : rôle de chaque relance.\n"
                        "- **Q4–Q6** : exemples de messages efficaces.\n"
                        "- **Q7–Q10** : erreurs et corrections.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un plan de relance complet pour un service choisi.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Réclamations & récupération",
            "supports": [
                {
                    "title": "Fiche de synthèse – Réclamations & récupération",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Réclamations & récupération\n\n"
                        "## Concepts clés à retenir\n"
                        "- Une réclamation mal gérée coûte plus qu’un geste commercial.\n"
                        "- Objectif : récupérer la confiance et éviter un avis négatif.\n"
                        "- Process en 3 temps : écouter, réparer, suivre.\n\n"
                        "## Définitions simples\n"
                        "- **Réclamation** : insatisfaction exprimée par la cliente.\n"
                        "- **Récupération** : action pour reconquérir la cliente.\n"
                        "- **Compensation** : geste mesuré (retouche, remise, soin).\n\n"
                        "## Règles importantes\n"
                        "- Répondre sous 24h.\n"
                        "- Proposer une solution claire et datée.\n"
                        "- Consigner chaque cas dans le CRM.\n\n"
                        "## Erreurs à éviter\n"
                        "- Répondre de manière défensive.\n"
                        "- Promettre sans agir rapidement.\n"
                        "- Laisser le prestataire gérer seul sans suivi manager.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Réclamations & récupération",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Réclamations & récupération\n\n"
                        "## Application concrète au salon\n"
                        "1. Écouter sans interrompre + noter le problème.\n"
                        "2. Reformuler pour valider la compréhension.\n"
                        "3. Proposer une solution : retouche, soin offert, remise contrôlée.\n"
                        "4. Fixer un délai d’action (ex: 48h).\n"
                        "5. Recontacter la cliente après résolution.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Utiliser un script d’excuse court et respectueux.\n"
                        "- Enregistrer le cas dans le CRM.\n"
                        "- Analyser la cause racine pour éviter la répétition.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure** : retouche gratuite + conseil entretien.\n"
                        "- **Make-up** : ajustement + geste commercial limité.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Réclamations & récupération",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Réclamations & récupération\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 3 étapes : écouter, réparer, suivre.\n"
                        "- Le rôle du manager et le délai de réponse.\n"
                        "- Les livrables : process SAV + script récupération.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et étapes.\n"
                        "- **Q4–Q6** : réponses attendues et scripts.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer une solution concrète et un suivi personnalisé.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Programme fidélité & parrainage",
            "supports": [
                {
                    "title": "Fiche de synthèse – Programme fidélité & parrainage",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Programme fidélité & parrainage\n\n"
                        "## Concepts clés à retenir\n"
                        "- Un programme simple = plus d’adhésion.\n"
                        "- Les récompenses doivent protéger la marge.\n"
                        "- Le parrainage attire des clientes similaires.\n\n"
                        "## Définitions simples\n"
                        "- **Fidélité** : bénéfice offert après un nombre de visites.\n"
                        "- **Parrainage** : cliente existante qui amène une nouvelle.\n"
                        "- **Récompense** : avantage mesuré (soin, remise limitée).\n\n"
                        "## Règles importantes\n"
                        "- 3 niveaux maximum (simple à comprendre).\n"
                        "- Récompense alignée sur les services phares.\n"
                        "- Suivi clair des gains dans le CRM.\n\n"
                        "## Erreurs à éviter\n"
                        "- Offrir des remises qui détruisent la marge.\n"
                        "- Trop de règles compliquées.\n"
                        "- Ne pas communiquer le programme aux clientes.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Programme fidélité & parrainage",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Programme fidélité & parrainage\n\n"
                        "## Application concrète au salon\n"
                        "1. Choisir 3 récompenses simples (ex: soin offert, remise 10%).\n"
                        "2. Définir la règle : “Après 3 visites”, “1 parrainage validé”.\n"
                        "3. Créer une carte fidélité digitale ou WhatsApp.\n"
                        "4. Former l’équipe à proposer le programme à l’encaissement.\n"
                        "5. Suivre les résultats chaque mois.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Écrire un message de parrainage prêt à diffuser.\n"
                        "- Afficher les règles à l’accueil.\n"
                        "- Lier la récompense à un service rentable.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure** : 5ème brushing à -50%.\n"
                        "- **Perruques** : entretien offert après 2 achats.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Programme fidélité & parrainage",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Programme fidélité & parrainage\n\n"
                        "## À maîtriser absolument\n"
                        "- Les objectifs d’un programme fidélité.\n"
                        "- Les règles simples et rentables.\n"
                        "- Les livrables : plan fidélité + règles de parrainage.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et principes.\n"
                        "- **Q4–Q6** : exemples de récompenses.\n"
                        "- **Q7–Q10** : erreurs à éviter et bonnes pratiques.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un programme simple pour un secteur choisi.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "WhatsApp stratégique",
            "supports": [
                {
                    "title": "Fiche de synthèse – WhatsApp stratégique",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – WhatsApp stratégique\n\n"
                        "## Concepts clés à retenir\n"
                        "- WhatsApp est le canal principal de relance et de conversion.\n"
                        "- Les étiquettes facilitent le suivi par segment.\n"
                        "- Un script court = plus de réponses.\n\n"
                        "## Définitions simples\n"
                        "- **Étiquette** : catégorie pour classer les conversations.\n"
                        "- **Script** : message prêt pour l’accueil, la relance, la vente.\n"
                        "- **Conversion** : passage du message au rendez-vous.\n\n"
                        "## Règles importantes\n"
                        "- Toujours personnaliser le prénom + service.\n"
                        "- 1 message = 1 objectif (relancer, qualifier, vendre).\n"
                        "- Répondre sous 30 minutes quand c’est possible.\n\n"
                        "## Erreurs à éviter\n"
                        "- Envoyer trop de messages sans réponse.\n"
                        "- Oublier de relancer les conversations ouvertes.\n"
                        "- Parler uniquement de promo sans valeur ajoutée.\n"
                    ),
                },
                {
                    "title": "Guide pratique – WhatsApp stratégique",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – WhatsApp stratégique\n\n"
                        "## Application concrète au salon\n"
                        "1. Créer 5 étiquettes : Nouveau lead, VIP, À relancer J+7, Dormante, RDV confirmé.\n"
                        "2. Préparer 3 scripts : accueil, relance, vente.\n"
                        "3. Utiliser un message court avec une question finale.\n"
                        "4. Noter dans le CRM le résultat de la conversation.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Script accueil : salutation + besoin + proposition.\n"
                        "- Script relance : rappel + bénéfice + action.\n"
                        "- Script vente : offre claire + disponibilité.\n\n"
                        "## Exemples Floxy Made\n"
                        "- “Bonjour [Prénom], votre lissage tient-il bien ? Souhaitez-vous une retouche cette semaine ?”\n"
                        "- “Nous avons une offre make-up événement samedi. Voulez-vous un créneau ?”\n"
                    ),
                },
                {
                    "title": "Guide de révision – WhatsApp stratégique",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – WhatsApp stratégique\n\n"
                        "## À maîtriser absolument\n"
                        "- Les étiquettes principales et leur usage.\n"
                        "- La structure d’un script efficace.\n"
                        "- Le rôle de WhatsApp dans la conversion.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : scripts et messages efficaces.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer une stratégie WhatsApp complète pour un service.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week2_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – CRM : fiches clientes et segmentation",
            "Guide pratique – CRM : fiches clientes et segmentation",
            "Guide de révision – CRM : fiches clientes et segmentation",
            "Fiche de synthèse – Suivi post-prestation J+1/J+7/J+21",
            "Guide pratique – Suivi post-prestation J+1/J+7/J+21",
            "Guide de révision – Suivi post-prestation J+1/J+7/J+21",
            "Fiche de synthèse – Réclamations & récupération",
            "Guide pratique – Réclamations & récupération",
            "Guide de révision – Réclamations & récupération",
            "Fiche de synthèse – Programme fidélité & parrainage",
            "Guide pratique – Programme fidélité & parrainage",
            "Guide de révision – Programme fidélité & parrainage",
            "Fiche de synthèse – WhatsApp stratégique",
            "Guide pratique – WhatsApp stratégique",
            "Guide de révision – WhatsApp stratégique",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_seed_week1_study_materials"),
    ]

    operations = [
        migrations.RunPython(seed_week2_study_materials, unseed_week2_study_materials),
    ]
