# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week3_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "Identité et ligne éditoriale",
            "supports": [
                {
                    "title": "Fiche de synthèse – Identité et ligne éditoriale",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Identité et ligne éditoriale\n\n"
                        "## Concepts clés à retenir\n"
                        "- L’identité Floxy Made doit être **cohérente** sur tous les supports.\n"
                        "- La ligne éditoriale guide **le ton, les messages et le style visuel**.\n"
                        "- Les contenus doivent refléter les secteurs clés : coiffure, perruques, make-up, onglerie, soins.\n\n"
                        "## Définitions simples\n"
                        "- **Positionnement** : ce qui rend Floxy Made unique aux yeux des clientes.\n"
                        "- **Ligne éditoriale** : règles de communication (ton, vocabulaire, thèmes).\n"
                        "- **Code visuel** : couleurs, polices, types d’images.\n\n"
                        "## Règles importantes\n"
                        "- 3 valeurs maximum à répéter partout (ex: expertise, élégance, confiance).\n"
                        "- 1 phrase de promesse claire pour tous les supports.\n"
                        "- Garder un style photo constant (lumière, cadrage, fond).\n\n"
                        "## Erreurs à éviter\n"
                        "- Changer de ton chaque semaine.\n"
                        "- Copier une marque concurrente.\n"
                        "- Publier sans cohérence visuelle.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Identité et ligne éditoriale",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Identité et ligne éditoriale\n\n"
                        "## Application concrète au salon\n"
                        "1. Choisir 3 mots qui décrivent Floxy Made (ex: premium, rassurant, moderne).\n"
                        "2. Définir une promesse client en 1 phrase.\n"
                        "3. Lister 5 messages clés par secteur (coiffure, perruques, etc.).\n"
                        "4. Créer un mini-guide visuel (couleurs + type de photo).\n"
                        "5. Valider le guide avec la direction puis l’imprimer.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Fixer le ton : professionnel + chaleureux + proche.\n"
                        "- Écrire 10 phrases types pour réseaux et WhatsApp.\n"
                        "- Mettre un modèle de post partagé à l’équipe.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure** : “Cheveux disciplinés, élégance immédiate.”\n"
                        "- **Perruques** : “Confiance et naturel pour chaque occasion.”\n"
                        "- **Make-up** : “Mise en valeur du visage sans excès.”\n"
                    ),
                },
                {
                    "title": "Guide de révision – Identité et ligne éditoriale",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Identité et ligne éditoriale\n\n"
                        "## À maîtriser absolument\n"
                        "- Positionnement + promesse client Floxy Made.\n"
                        "- 3 valeurs clés et le ton associé.\n"
                        "- Livrable : guide identité + messages clés.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et rôle de la ligne éditoriale.\n"
                        "- **Q4–Q6** : cohérence visuelle et messages clés.\n"
                        "- **Q7–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer un mini-guide éditorial pour un secteur.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Piliers de contenu : transformation, éducation, preuve",
            "supports": [
                {
                    "title": "Fiche de synthèse – Piliers de contenu",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Piliers de contenu\n\n"
                        "## Concepts clés à retenir\n"
                        "- 3 piliers : **Transformation**, **Éducation**, **Preuve**.\n"
                        "- Chaque pilier répond à un objectif client.\n"
                        "- L’équilibre évite un feed 100% promo.\n\n"
                        "## Définitions simples\n"
                        "- **Transformation** : avant/après, résultats visibles.\n"
                        "- **Éducation** : conseils, astuces, explications simples.\n"
                        "- **Preuve** : avis clientes, témoignages, coulisses.\n\n"
                        "## Règles importantes\n"
                        "- Minimum 3 idées par pilier chaque semaine.\n"
                        "- Toujours demander l’accord pour publier un avant/après.\n"
                        "- Montrer des preuves réelles (avis, photos, chiffres).\n\n"
                        "## Erreurs à éviter\n"
                        "- Publier uniquement des promotions.\n"
                        "- Utiliser des images non réelles.\n"
                        "- Négliger les témoignages clientes.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Piliers de contenu",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Piliers de contenu\n\n"
                        "## Application concrète au salon\n"
                        "1. Créer un tableau avec 3 colonnes (Transformation/Éducation/Preuve).\n"
                        "2. Remplir 5 idées par colonne.\n"
                        "3. Associer chaque idée à un secteur (coiffure, perruques, etc.).\n"
                        "4. Planifier 1 post par pilier chaque semaine.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Transformation : photo avant/après + mini-texte.\n"
                        "- Éducation : 3 conseils simples en carrousel.\n"
                        "- Preuve : témoignage client + résultat photo.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Transformation** : avant/après lissage brésilien.\n"
                        "- **Éducation** : comment entretenir une perruque lace.\n"
                        "- **Preuve** : avis cliente make-up mariage.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Piliers de contenu",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Piliers de contenu\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 3 piliers et leur objectif.\n"
                        "- Exemples concrets par secteur.\n"
                        "- Livrable : checklist formats par pilier.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définition des piliers.\n"
                        "- **Q4–Q6** : exemples par secteur.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un planning de contenus équilibré.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Création de vidéos courtes (Reels, TikTok)",
            "supports": [
                {
                    "title": "Fiche de synthèse – Création de vidéos courtes",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Création de vidéos courtes\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les 3 premières secondes décident de la rétention.\n"
                        "- Format vertical 9:16, durée idéale 15–30s.\n"
                        "- Lumière et stabilité sont prioritaires.\n\n"
                        "## Définitions simples\n"
                        "- **Hook** : phrase/visuel d’accroche immédiate.\n"
                        "- **B-roll** : plans rapides pour illustrer l’action.\n"
                        "- **CTA** : invitation à réserver ou contacter.\n\n"
                        "## Règles importantes\n"
                        "- Filmer près d’une lumière naturelle.\n"
                        "- Couper les temps morts au montage.\n"
                        "- Ajouter un texte court à l’écran.\n\n"
                        "## Erreurs à éviter\n"
                        "- Vidéos trop longues sans rythme.\n"
                        "- Mauvais son ou image sombre.\n"
                        "- Oublier d’indiquer le service.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Création de vidéos courtes",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Création de vidéos courtes\n\n"
                        "## Application concrète au salon\n"
                        "1. Écrire un script en 3 lignes (Hook → Action → Résultat).\n"
                        "2. Filmer 3 plans : avant, action, résultat.\n"
                        "3. Ajouter un texte court “Résultat en 20 min”.\n"
                        "4. Publier avec un CTA : “Réservez sur WhatsApp”.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Préparer le téléphone (stabilisateur ou trépied).\n"
                        "- Filmer en lumière naturelle près de la vitrine.\n"
                        "- Monter avec une application simple (CapCut).\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Perruques** : pose + coiffage en 20s.\n"
                        "- **Onglerie** : avant/après avec zoom sur détails.\n"
                        "- **Coiffure** : lissage accéléré + résultat final.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Création de vidéos courtes",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Création de vidéos courtes\n\n"
                        "## À maîtriser absolument\n"
                        "- Structure Hook → Action → Résultat.\n"
                        "- Durée idéale et format vertical.\n"
                        "- Livrable : plan de tournage + checklist.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : hook, format et durée.\n"
                        "- **Q4–Q6** : lumière, montage, texte.\n"
                        "- **Q7–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer 2 scripts vidéo pour un service.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Captions orientées conversion",
            "supports": [
                {
                    "title": "Fiche de synthèse – Captions orientées conversion",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Captions orientées conversion\n\n"
                        "## Concepts clés à retenir\n"
                        "- Une bonne caption = **Hook + Valeur + Preuve + CTA**.\n"
                        "- Le texte doit être court, clair et orienté action.\n"
                        "- Une seule action demandée.\n\n"
                        "## Définitions simples\n"
                        "- **Hook** : phrase d’accroche immédiate.\n"
                        "- **Preuve** : avis cliente, résultat, chiffre.\n"
                        "- **CTA** : appel à l’action (réserver, écrire, appeler).\n\n"
                        "## Règles importantes\n"
                        "- 3 lignes max avant “voir plus”.\n"
                        "- Utiliser des mots simples et directs.\n"
                        "- Mentionner le service et le résultat.\n\n"
                        "## Erreurs à éviter\n"
                        "- Caption trop longue sans CTA.\n"
                        "- Trop d’emojis ou hashtags.\n"
                        "- Ne pas parler du bénéfice client.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Captions orientées conversion",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Captions orientées conversion\n\n"
                        "## Application concrète au salon\n"
                        "1. Écrire 10 hooks adaptés aux secteurs.\n"
                        "2. Ajouter une phrase de valeur (bénéfice client).\n"
                        "3. Insérer une preuve (avis, résultat, avant/après).\n"
                        "4. Terminer par un CTA unique.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Modèle : Hook → Valeur → Preuve → CTA.\n"
                        "- Garder 2–3 phrases max avant “voir plus”.\n"
                        "- Tester 2 CTA par semaine.\n\n"
                        "## Exemples Floxy Made\n"
                        "- “Cheveux lisses 3 mois ✅ Réservez votre lissage aujourd’hui.”\n"
                        "- “Perruque naturelle en 30 min. Écrivez ‘PERRUQUE’ sur WhatsApp.”\n"
                    ),
                },
                {
                    "title": "Guide de révision – Captions orientées conversion",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Captions orientées conversion\n\n"
                        "## À maîtriser absolument\n"
                        "- La structure Hook → Valeur → Preuve → CTA.\n"
                        "- Le rôle d’un CTA unique.\n"
                        "- Livrables : bibliothèque de hooks + templates.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : structure et définitions.\n"
                        "- **Q4–Q6** : exemples de captions efficaces.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Écrire 3 captions prêtes à publier.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Planification via calendrier éditorial",
            "supports": [
                {
                    "title": "Fiche de synthèse – Planification via calendrier éditorial",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Planification via calendrier éditorial\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le calendrier éditorial évite l’improvisation.\n"
                        "- Il répartit les piliers de contenu sur 4 semaines.\n"
                        "- Il clarifie qui produit, qui valide et qui publie.\n\n"
                        "## Définitions simples\n"
                        "- **Calendrier éditorial** : planning des contenus à publier.\n"
                        "- **Piliers** : transformation, éducation, preuve.\n"
                        "- **Slot** : créneau précis de publication.\n\n"
                        "## Règles importantes\n"
                        "- Préparer au moins 2 semaines à l’avance.\n"
                        "- Prévoir 1 jour de production par semaine.\n"
                        "- Conserver un équilibre entre les piliers.\n\n"
                        "## Erreurs à éviter\n"
                        "- Publier au jour le jour sans plan.\n"
                        "- Tout produire à la dernière minute.\n"
                        "- Oublier de valider les contenus.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Planification via calendrier éditorial",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Planification via calendrier éditorial\n\n"
                        "## Application concrète au salon\n"
                        "1. Fixer 3 jours de publication par semaine.\n"
                        "2. Associer chaque post à un pilier.\n"
                        "3. Définir responsable (tournage, montage, validation).\n"
                        "4. Préparer les contenus la semaine précédente.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Créer un tableau simple (date, pilier, format, responsable).\n"
                        "- Intégrer 1 contenu preuve chaque semaine.\n"
                        "- Planifier les tournages à heure fixe.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Lundi : transformation coiffure.\n"
                        "- Mercredi : astuce entretien perruque.\n"
                        "- Samedi : avis cliente make-up.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Planification via calendrier éditorial",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Planification via calendrier éditorial\n\n"
                        "## À maîtriser absolument\n"
                        "- Objectif d’un calendrier éditorial.\n"
                        "- Répartition équilibrée des piliers.\n"
                        "- Livrable : calendrier éditorial 4 semaines.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : organisation et responsabilités.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un planning 1 semaine avec 3 contenus.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week3_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – Identité et ligne éditoriale",
            "Guide pratique – Identité et ligne éditoriale",
            "Guide de révision – Identité et ligne éditoriale",
            "Fiche de synthèse – Piliers de contenu",
            "Guide pratique – Piliers de contenu",
            "Guide de révision – Piliers de contenu",
            "Fiche de synthèse – Création de vidéos courtes",
            "Guide pratique – Création de vidéos courtes",
            "Guide de révision – Création de vidéos courtes",
            "Fiche de synthèse – Captions orientées conversion",
            "Guide pratique – Captions orientées conversion",
            "Guide de révision – Captions orientées conversion",
            "Fiche de synthèse – Planification via calendrier éditorial",
            "Guide pratique – Planification via calendrier éditorial",
            "Guide de révision – Planification via calendrier éditorial",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0008_seed_week2_study_materials"),
    ]

    operations = [
        migrations.RunPython(seed_week3_study_materials, unseed_week3_study_materials),
    ]
