# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week4_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "Optimisation des profils sociaux",
            "supports": [
                {
                    "title": "Fiche de synthèse – Optimisation des profils sociaux",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Optimisation des profils sociaux\n\n"
                        "## Concepts clés à retenir\n"
                        "- Un profil optimisé augmente la conversion des visiteurs.\n"
                        "- La bio doit être claire, courte et orientée service.\n"
                        "- Le lien RDV est indispensable.\n\n"
                        "## Définitions simples\n"
                        "- **Bio** : présentation courte qui explique ce que vous faites.\n"
                        "- **Highlights** : bulles qui classent services et résultats.\n"
                        "- **Lien RDV** : accès rapide à la prise de rendez-vous.\n\n"
                        "## Règles importantes\n"
                        "- Mettre le service principal dès la première ligne.\n"
                        "- Ajouter une preuve (avis, nombre de clientes, résultats).\n"
                        "- Mettre un CTA clair : “Réservez via WhatsApp”.\n\n"
                        "## Erreurs à éviter\n"
                        "- Bio trop longue ou floue.\n"
                        "- Pas de lien de réservation.\n"
                        "- Photos de profil non professionnelles.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Optimisation des profils sociaux",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Optimisation des profils sociaux\n\n"
                        "## Application concrète au salon\n"
                        "1. Écrire une bio en 3 lignes : service, preuve, CTA.\n"
                        "2. Ajouter un lien direct WhatsApp / prise de RDV.\n"
                        "3. Créer 4 highlights : Coiffure, Perruques, Make-up, Avis.\n"
                        "4. Choisir une photo de profil claire et lumineuse.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Standardiser le nom d’utilisateur.\n"
                        "- Mettre en avant le secteur le plus rentable.\n"
                        "- Actualiser les highlights chaque mois.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Bio : “Lissage, perruques, make-up. 5★ Avis clients. RDV WhatsApp.”\n"
                        "- Highlight “Avis” avec 5 retours clients récents.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Optimisation des profils sociaux",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Optimisation des profils sociaux\n\n"
                        "## À maîtriser absolument\n"
                        "- Structure d’une bio efficace.\n"
                        "- Rôle des highlights et du lien RDV.\n"
                        "- Livrable : checklist optimisation profils.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : éléments indispensables du profil.\n"
                        "- **Q4–Q6** : exemples de bio/CTA.\n"
                        "- **Q7–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Optimiser le profil Instagram d’un secteur Floxy Made.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Stratégies de croissance locale",
            "supports": [
                {
                    "title": "Fiche de synthèse – Stratégies de croissance locale",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Stratégies de croissance locale\n\n"
                        "## Concepts clés à retenir\n"
                        "- La croissance locale vient des hashtags, géolocalisation et partenariats.\n"
                        "- Les collaborations locales apportent des clientes qualifiées.\n"
                        "- Chaque secteur doit avoir ses hashtags propres.\n\n"
                        "## Définitions simples\n"
                        "- **Hashtag local** : #YopougonCoiffure, #AbidjanMakeup.\n"
                        "- **Géolocalisation** : taguer la commune ou le quartier.\n"
                        "- **Partenariat** : échange de visibilité avec un business local.\n\n"
                        "## Règles importantes\n"
                        "- 5 à 10 hashtags locaux par post.\n"
                        "- Taguer la localisation à chaque publication.\n"
                        "- Planifier 1 collaboration par mois.\n\n"
                        "## Erreurs à éviter\n"
                        "- Utiliser des hashtags trop génériques.\n"
                        "- Collaborer avec des comptes non alignés.\n"
                        "- Oublier de mesurer les résultats.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Stratégies de croissance locale",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Stratégies de croissance locale\n\n"
                        "## Application concrète au salon\n"
                        "1. Lister 10 hashtags locaux par secteur.\n"
                        "2. Identifier 5 partenaires potentiels (boutiques, photographes, wedding planners).\n"
                        "3. Proposer une collaboration : post croisé ou offre spéciale.\n"
                        "4. Taguer systématiquement la localisation Floxy Made.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Créer une liste hashtag par service.\n"
                        "- Organiser un mini-shooting avec un partenaire.\n"
                        "- Mesurer les nouveaux abonnés et demandes.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Partenariat avec un studio photo local pour make-up mariage.\n"
                        "- Collaboration avec une boutique mode pour perruques.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Stratégies de croissance locale",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Stratégies de croissance locale\n\n"
                        "## À maîtriser absolument\n"
                        "- Rôle des hashtags locaux et de la géolocalisation.\n"
                        "- Importance des partenariats ciblés.\n"
                        "- Livrable : plan de collaborations mensuel.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : hashtags + géolocalisation.\n"
                        "- **Q4–Q6** : partenariats et exemples.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer 1 collaboration locale avec plan d’action.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Gestion des DM & prise de rendez-vous",
            "supports": [
                {
                    "title": "Fiche de synthèse – Gestion des DM & prise de rendez-vous",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Gestion des DM & prise de rendez-vous\n\n"
                        "## Concepts clés à retenir\n"
                        "- Un DM doit qualifier le besoin et proposer un RDV.\n"
                        "- La rapidité de réponse augmente la conversion.\n"
                        "- Le script DM doit suivre 4 étapes.\n\n"
                        "## Définitions simples\n"
                        "- **Qualification** : comprendre le besoin, budget, délai.\n"
                        "- **Offre** : proposition claire (service + prix + dispo).\n"
                        "- **Conversion** : passage du DM au RDV fixé.\n\n"
                        "## Règles importantes\n"
                        "- Répondre en moins de 30 minutes quand possible.\n"
                        "- Toujours terminer par une proposition de créneau.\n"
                        "- Noter le résultat dans le CRM.\n\n"
                        "## Erreurs à éviter\n"
                        "- Répondre sans proposer d’action.\n"
                        "- Donner trop d’informations sans conclure.\n"
                        "- Oublier le suivi si la cliente ne répond pas.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Gestion des DM & prise de rendez-vous",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Gestion des DM & prise de rendez-vous\n\n"
                        "## Application concrète au salon\n"
                        "1. Utiliser un script en 4 étapes : accueil, besoin, offre, RDV.\n"
                        "2. Proposer 2 créneaux clairs.\n"
                        "3. Confirmer le RDV et rappeler l’adresse.\n"
                        "4. Enregistrer dans le CRM.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Exemple : “Bonjour, quel service souhaitez-vous ?”\n"
                        "- Proposer un prix et une durée.\n"
                        "- Confirmer la réservation par message.\n\n"
                        "## Exemples Floxy Made\n"
                        "- “Lissage disponible jeudi 10h ou samedi 15h, quel créneau préférez-vous ?”\n"
                        "- “Pose perruque demain 14h, confirmez votre venue.”\n"
                    ),
                },
                {
                    "title": "Guide de révision – Gestion des DM & prise de rendez-vous",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Gestion des DM & prise de rendez-vous\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 4 étapes du script DM.\n"
                        "- Comment transformer un DM en RDV.\n"
                        "- Livrable : script DM complet + checklist RDV.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : étapes et définitions.\n"
                        "- **Q4–Q6** : exemples de réponses.\n"
                        "- **Q7–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Simuler un échange DM complet.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Offres hebdomadaires & promotions ciblées",
            "supports": [
                {
                    "title": "Fiche de synthèse – Offres hebdomadaires & promotions ciblées",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Offres hebdomadaires & promotions ciblées\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les offres doivent être limitées dans le temps.\n"
                        "- Chaque promotion doit protéger la marge.\n"
                        "- Les promos sont ciblées par secteur/service.\n\n"
                        "## Définitions simples\n"
                        "- **Offre hebdo** : promo valable 7 jours.\n"
                        "- **Promo ciblée** : offre adaptée à un secteur précis.\n"
                        "- **Marge** : différence entre coût et prix de vente.\n\n"
                        "## Règles importantes\n"
                        "- Toujours calculer la marge avant diffusion.\n"
                        "- 1 offre = 1 objectif (remplir le planning).\n"
                        "- Communiquer clairement la durée de validité.\n\n"
                        "## Erreurs à éviter\n"
                        "- Faire des promos trop fréquentes.\n"
                        "- Proposer des prix non rentables.\n"
                        "- Oublier de mesurer l’impact.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Offres hebdomadaires & promotions ciblées",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Offres hebdomadaires & promotions ciblées\n\n"
                        "## Application concrète au salon\n"
                        "1. Identifier un service faible à remplir.\n"
                        "2. Proposer une offre courte (ex: -15% du lundi au mercredi).\n"
                        "3. Vérifier la marge minimale.\n"
                        "4. Diffuser sur WhatsApp + réseaux.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Préparer un calendrier promo sur 4 semaines.\n"
                        "- Créer un visuel simple par offre.\n"
                        "- Mesurer le nombre de RDV générés.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Offre lissage + soin profond du lundi au jeudi.\n"
                        "- Promo make-up express pour week-end.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Offres hebdomadaires & promotions ciblées",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Offres hebdomadaires & promotions ciblées\n\n"
                        "## À maîtriser absolument\n"
                        "- Calculer la marge avant une promo.\n"
                        "- Le format “offre limitée”.\n"
                        "- Livrables : calendrier promos + modèles d’offres.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : objectifs et définitions.\n"
                        "- **Q4–Q6** : marge et durée.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire une offre hebdomadaire rentable.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week4_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – Optimisation des profils sociaux",
            "Guide pratique – Optimisation des profils sociaux",
            "Guide de révision – Optimisation des profils sociaux",
            "Fiche de synthèse – Stratégies de croissance locale",
            "Guide pratique – Stratégies de croissance locale",
            "Guide de révision – Stratégies de croissance locale",
            "Fiche de synthèse – Gestion des DM & prise de rendez-vous",
            "Guide pratique – Gestion des DM & prise de rendez-vous",
            "Guide de révision – Gestion des DM & prise de rendez-vous",
            "Fiche de synthèse – Offres hebdomadaires & promotions ciblées",
            "Guide pratique – Offres hebdomadaires & promotions ciblées",
            "Guide de révision – Offres hebdomadaires & promotions ciblées",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_seed_week3_study_materials"),
    ]

    operations = [
        migrations.RunPython(seed_week4_study_materials, unseed_week4_study_materials),
    ]
