# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week5_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "Offres packagées & bundles",
            "supports": [
                {
                    "title": "Fiche de synthèse – Offres packagées & bundles",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Offres packagées & bundles\n\n"
                        "## Concepts clés à retenir\n"
                        "- Un bundle regroupe plusieurs services pour augmenter le panier moyen.\n"
                        "- Les bundles doivent rester simples et lisibles.\n"
                        "- Chaque pack doit protéger la marge.\n\n"
                        "## Définitions simples\n"
                        "- **Bundle** : offre combinée (ex: coiffure + soin).\n"
                        "- **Pack événementiel** : offre spéciale pour occasions (mariage, fête).\n"
                        "- **Argumentaire** : phrases qui expliquent pourquoi le pack est avantageux.\n\n"
                        "## Règles importantes\n"
                        "- 2 à 3 services maximum par pack.\n"
                        "- Toujours afficher l’économie réelle pour la cliente.\n"
                        "- Tester d’abord avec un secteur (ex: coiffure).\n\n"
                        "## Erreurs à éviter\n"
                        "- Packs trop complexes ou trop chers.\n"
                        "- Bundles qui cannibalisent les services unitaires.\n"
                        "- Oublier d’expliquer la valeur du pack.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Offres packagées & bundles",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Offres packagées & bundles\n\n"
                        "## Application concrète au salon\n"
                        "1. Sélectionner 3 services qui se complètent.\n"
                        "2. Calculer le prix pack (prix total - réduction légère).\n"
                        "3. Rédiger 3 arguments de valeur.\n"
                        "4. Tester le pack sur 10 clientes.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Créer un catalogue de bundles.\n"
                        "- Afficher les packs à l’accueil et sur WhatsApp.\n"
                        "- Former l’équipe à proposer le pack au bon moment.\n\n"
                        "## Exemples Floxy Made\n"
                        "- **Coiffure + soin profond**.\n"
                        "- **Pose perruque + entretien**.\n"
                        "- **Make-up + coiffure événement**.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Offres packagées & bundles",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Offres packagées & bundles\n\n"
                        "## À maîtriser absolument\n"
                        "- Ce qu’est un bundle et son objectif.\n"
                        "- Comment fixer un prix rentable.\n"
                        "- Livrables : catalogue bundles + argumentaire.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : critères d’un pack efficace.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un pack pour un secteur choisi.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Upsell & cross-sell",
            "supports": [
                {
                    "title": "Fiche de synthèse – Upsell & cross-sell",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Upsell & cross-sell\n\n"
                        "## Concepts clés à retenir\n"
                        "- L’upsell propose une version supérieure du service.\n"
                        "- Le cross-sell propose un service complémentaire.\n"
                        "- L’objectif est d’augmenter le panier moyen sans frustrer la cliente.\n\n"
                        "## Définitions simples\n"
                        "- **Upsell** : proposer mieux (ex: soin premium).\n"
                        "- **Cross-sell** : proposer en complément (ex: entretien).\n"
                        "- **Moment clé** : instant où la cliente est la plus réceptive.\n\n"
                        "## Règles importantes\n"
                        "- Toujours relier l’offre au besoin client.\n"
                        "- Proposer au moment du diagnostic ou de la fin de prestation.\n"
                        "- 1 proposition claire, pas plusieurs.\n\n"
                        "## Erreurs à éviter\n"
                        "- Forcer la cliente.\n"
                        "- Proposer des services non pertinents.\n"
                        "- Parler uniquement de prix sans bénéfice.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Upsell & cross-sell",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Upsell & cross-sell\n\n"
                        "## Application concrète au salon\n"
                        "1. Créer une liste de 5 upsells par secteur.\n"
                        "2. Associer 1 cross-sell simple par service.\n"
                        "3. Former l’équipe avec un script court.\n"
                        "4. Mesurer l’impact sur le panier moyen.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Upsell : “Souhaitez-vous le soin premium ?”\n"
                        "- Cross-sell : “Voulez-vous ajouter le traitement entretien ?”\n"
                        "- Noter la réaction client dans le CRM.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Lissage + soin profond.\n"
                        "- Perruque + kit entretien.\n"
                        "- Make-up + faux cils.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Upsell & cross-sell",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Upsell & cross-sell\n\n"
                        "## À maîtriser absolument\n"
                        "- Différence entre upsell et cross-sell.\n"
                        "- Moment idéal pour proposer.\n"
                        "- Livrable : liste d’upsell par service.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions.\n"
                        "- **Q4–Q6** : exemples concrets.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire une proposition upsell et cross-sell.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Objectifs hebdomadaires & suivi CA",
            "supports": [
                {
                    "title": "Fiche de synthèse – Objectifs hebdomadaires & suivi CA",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Objectifs hebdomadaires & suivi CA\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les objectifs hebdo guident les actions de l’équipe.\n"
                        "- Le suivi quotidien évite les mauvaises surprises.\n"
                        "- Chaque secteur a son objectif chiffré.\n\n"
                        "## Définitions simples\n"
                        "- **Objectif hebdo** : cible de CA sur 7 jours.\n"
                        "- **Suivi quotidien** : contrôle rapide des résultats.\n"
                        "- **Reporting** : résumé simple des chiffres et actions.\n\n"
                        "## Règles importantes\n"
                        "- 1 objectif par secteur (coiffure, perruques, etc.).\n"
                        "- Mettre à jour le suivi chaque jour.\n"
                        "- Réagir rapidement si l’écart est important.\n\n"
                        "## Erreurs à éviter\n"
                        "- Fixer des objectifs irréalistes.\n"
                        "- Suivre uniquement en fin de semaine.\n"
                        "- Ne pas partager les chiffres avec l’équipe.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Objectifs hebdomadaires & suivi CA",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Objectifs hebdomadaires & suivi CA\n\n"
                        "## Application concrète au salon\n"
                        "1. Fixer un objectif CA par secteur.\n"
                        "2. Tenir un tableau de suivi quotidien (papier ou digital).\n"
                        "3. Faire un point rapide chaque matin.\n"
                        "4. Ajuster les actions si retard (promo ciblée, relance).\n\n"
                        "## Étapes opérationnelles\n"
                        "- Écrire les objectifs visibles pour l’équipe.\n"
                        "- Comparer réalisé vs objectif chaque jour.\n"
                        "- Ajouter une action corrective simple.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Coiffure : 200k CFA / semaine.\n"
                        "- Perruques : 3 ventes / semaine.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Objectifs hebdomadaires & suivi CA",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Objectifs hebdomadaires & suivi CA\n\n"
                        "## À maîtriser absolument\n"
                        "- Pourquoi fixer des objectifs par secteur.\n"
                        "- Comment suivre le CA quotidiennement.\n"
                        "- Livrables : tableau objectifs + rituel de suivi.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : suivi quotidien.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un tableau de suivi hebdo.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Management des prestataires",
            "supports": [
                {
                    "title": "Fiche de synthèse – Management des prestataires",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Management des prestataires\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le manager doit cadrer la qualité et la motivation.\n"
                        "- Le brief quotidien évite les erreurs.\n"
                        "- Les critères qualité sont clairs et partagés.\n\n"
                        "## Définitions simples\n"
                        "- **Brief** : réunion courte avant la journée.\n"
                        "- **Contrôle qualité** : vérification du travail fini.\n"
                        "- **Motivation** : reconnaissance et suivi des résultats.\n\n"
                        "## Règles importantes\n"
                        "- Brief court (10 min) chaque début de journée.\n"
                        "- Contrôle qualité systématique sur services clés.\n"
                        "- Feedback immédiat après prestation.\n\n"
                        "## Erreurs à éviter\n"
                        "- Laisser les prestataires sans consignes.\n"
                        "- Critiquer sans proposer de solution.\n"
                        "- Ne pas suivre la performance individuelle.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Management des prestataires",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Management des prestataires\n\n"
                        "## Application concrète au salon\n"
                        "1. Planifier un briefing hebdo + brief quotidien rapide.\n"
                        "2. Définir 3 critères qualité (ex: propreté, temps, résultat).\n"
                        "3. Contrôler 1 prestation par prestataire chaque jour.\n"
                        "4. Donner un feedback immédiat.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Mettre en place une checklist briefing.\n"
                        "- Utiliser un tableau de suivi individuel.\n"
                        "- Valoriser les meilleures performances.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Vérifier la tenue du make-up après prestation.\n"
                        "- Contrôler la coupe perruque avant validation.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Management des prestataires",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Management des prestataires\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 3 critères qualité minimum.\n"
                        "- L’importance du brief quotidien.\n"
                        "- Livrables : checklist briefing + plan motivation.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : pratiques de contrôle qualité.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer un plan simple de management d’équipe.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week5_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – Offres packagées & bundles",
            "Guide pratique – Offres packagées & bundles",
            "Guide de révision – Offres packagées & bundles",
            "Fiche de synthèse – Upsell & cross-sell",
            "Guide pratique – Upsell & cross-sell",
            "Guide de révision – Upsell & cross-sell",
            "Fiche de synthèse – Objectifs hebdomadaires & suivi CA",
            "Guide pratique – Objectifs hebdomadaires & suivi CA",
            "Guide de révision – Objectifs hebdomadaires & suivi CA",
            "Fiche de synthèse – Management des prestataires",
            "Guide pratique – Management des prestataires",
            "Guide de révision – Management des prestataires",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0010_seed_week4_study_materials"),
    ]

    operations = [
        migrations.RunPython(seed_week5_study_materials, unseed_week5_study_materials),
    ]
