# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_week6_study_materials(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")

    materials = [
        {
            "lesson_title": "Lecture et analyse des KPI",
            "supports": [
                {
                    "title": "Fiche de synthèse – Lecture et analyse des KPI",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Lecture et analyse des KPI\n\n"
                        "## Concepts clés à retenir\n"
                        "- Les KPI montrent ce qui fonctionne ou non.\n"
                        "- Il faut suivre ventes, rétention et marketing.\n"
                        "- Un KPI doit être lisible et actionnable.\n\n"
                        "## Définitions simples\n"
                        "- **KPI ventes** : CA par secteur, panier moyen.\n"
                        "- **KPI rétention** : taux de retour, clientes actives.\n"
                        "- **KPI marketing** : demandes WhatsApp, conversion DM.\n\n"
                        "## Règles importantes\n"
                        "- Suivre 5 KPI max pour rester focus.\n"
                        "- Comparer semaine N vs N-1.\n"
                        "- Toujours proposer une action après l’analyse.\n\n"
                        "## Erreurs à éviter\n"
                        "- Suivre trop d’indicateurs.\n"
                        "- Analyser sans décider d’actions.\n"
                        "- Oublier les KPI par secteur.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Lecture et analyse des KPI",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Lecture et analyse des KPI\n\n"
                        "## Application concrète au salon\n"
                        "1. Choisir 5 KPI clés (CA, panier moyen, retour client, DM, RDV).\n"
                        "2. Noter les chiffres chaque semaine.\n"
                        "3. Comparer à la semaine précédente.\n"
                        "4. Décider d’une action corrective si baisse.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Utiliser un tableau simple KPI.\n"
                        "- Faire un point KPI chaque lundi.\n"
                        "- Partager la synthèse avec l’équipe.\n\n"
                        "## Exemples Floxy Made\n"
                        "- CA coiffure en baisse → relance WhatsApp ciblée.\n"
                        "- Taux retour perruques faible → offre entretien.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Lecture et analyse des KPI",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Lecture et analyse des KPI\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 5 KPI principaux.\n"
                        "- Comment lire une variation.\n"
                        "- Livrable : liste KPI + analyse écarts.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions KPI.\n"
                        "- **Q4–Q6** : analyse et actions.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire une analyse simple avec 2 actions.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Reporting hebdomadaire",
            "supports": [
                {
                    "title": "Fiche de synthèse – Reporting hebdomadaire",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Reporting hebdomadaire\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le reporting doit tenir sur 1 page.\n"
                        "- Il résume chiffres, actions et décisions.\n"
                        "- Il sert à piloter la semaine suivante.\n\n"
                        "## Définitions simples\n"
                        "- **Reporting** : synthèse hebdomadaire de la performance.\n"
                        "- **Plan d’action** : 2–3 actions prioritaires à suivre.\n"
                        "- **Rituel** : moment fixe pour le reporting.\n\n"
                        "## Règles importantes\n"
                        "- 1 page maximum.\n"
                        "- Toujours inclure KPI + actions.\n"
                        "- Partager à la direction chaque semaine.\n\n"
                        "## Erreurs à éviter\n"
                        "- Reporting trop long.\n"
                        "- Faire du reporting sans plan d’action.\n"
                        "- Oublier de le partager.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Reporting hebdomadaire",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Reporting hebdomadaire\n\n"
                        "## Application concrète au salon\n"
                        "1. Collecter les KPI de la semaine.\n"
                        "2. Résumer les points forts et points faibles.\n"
                        "3. Proposer 3 actions prioritaires.\n"
                        "4. Envoyer le reporting chaque lundi matin.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Utiliser un template unique.\n"
                        "- Fixer un créneau dédié au reporting.\n"
                        "- Archiver les reportings pour suivi.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Action : booster ventes make-up avec promo week-end.\n"
                        "- Action : relance clientes dormantes.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Reporting hebdomadaire",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Reporting hebdomadaire\n\n"
                        "## À maîtriser absolument\n"
                        "- Structure d’un reporting 1 page.\n"
                        "- Comment résumer KPI + actions.\n"
                        "- Livrable : template reporting + rituel hebdo.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définitions et objectifs.\n"
                        "- **Q4–Q6** : contenu et structure.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Rédiger un reporting synthétique.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Tableau de bord global",
            "supports": [
                {
                    "title": "Fiche de synthèse – Tableau de bord global",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Tableau de bord global\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le dashboard centralise CRM, ventes et marketing.\n"
                        "- Il sert à piloter la performance en un coup d’œil.\n"
                        "- Les indicateurs doivent être mis à jour régulièrement.\n\n"
                        "## Définitions simples\n"
                        "- **Dashboard** : tableau regroupant KPI et tendances.\n"
                        "- **Vue CRM** : leads, clientes actives, taux de retour.\n"
                        "- **Vue ventes** : CA par secteur, panier moyen.\n\n"
                        "## Règles importantes\n"
                        "- Consulter le dashboard chaque semaine.\n"
                        "- Identifier 1 KPI rouge et agir.\n"
                        "- Partager les résultats clés avec l’équipe.\n\n"
                        "## Erreurs à éviter\n"
                        "- Ne pas mettre à jour les données.\n"
                        "- Avoir trop d’indicateurs inutiles.\n"
                        "- Ignorer les alertes du dashboard.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Tableau de bord global",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Tableau de bord global\n\n"
                        "## Application concrète au salon\n"
                        "1. Ouvrir le dashboard chaque lundi.\n"
                        "2. Noter les KPI rouges en priorité.\n"
                        "3. Fixer 1 action corrective par KPI rouge.\n"
                        "4. Partager un mini-récap à l’équipe.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Vérifier la vue CRM et la vue ventes.\n"
                        "- Comparer semaine N/N-1.\n"
                        "- Mettre à jour le plan d’action.\n\n"
                        "## Exemples Floxy Made\n"
                        "- KPI “DM→RDV” en baisse → script de relance.\n"
                        "- KPI “panier moyen” en baisse → upsell ciblé.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Tableau de bord global",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Tableau de bord global\n\n"
                        "## À maîtriser absolument\n"
                        "- Les 3 vues principales (CRM, ventes, marketing).\n"
                        "- Comment interpréter un KPI rouge.\n"
                        "- Livrable : checklist dashboard + routine.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : rôle du dashboard.\n"
                        "- **Q4–Q6** : lecture des KPI.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer un plan d’amélioration basé sur le dashboard.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Plan d'actions 90 jours",
            "supports": [
                {
                    "title": "Fiche de synthèse – Plan d'actions 90 jours",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Plan d'actions 90 jours\n\n"
                        "## Concepts clés à retenir\n"
                        "- Le plan 90 jours fixe des priorités claires.\n"
                        "- Il contient objectifs, actions et suivi mensuel.\n"
                        "- 3 objectifs majeurs maximum.\n\n"
                        "## Définitions simples\n"
                        "- **Plan 90 jours** : feuille de route trimestrielle.\n"
                        "- **Priorité** : action à fort impact.\n"
                        "- **KPI de suivi** : indicateur pour vérifier l’avancement.\n\n"
                        "## Règles importantes\n"
                        "- Fixer 3 objectifs majeurs max.\n"
                        "- Lister 5 actions prioritaires.\n"
                        "- Réviser le plan chaque mois.\n\n"
                        "## Erreurs à éviter\n"
                        "- Trop d’objectifs à la fois.\n"
                        "- Plan non suivi après création.\n"
                        "- Actions sans indicateurs.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Plan d'actions 90 jours",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Plan d'actions 90 jours\n\n"
                        "## Application concrète au salon\n"
                        "1. Choisir 3 objectifs majeurs (CA, fidélité, visibilité).\n"
                        "2. Associer 5 actions prioritaires.\n"
                        "3. Définir un responsable et une date par action.\n"
                        "4. Fixer un KPI de suivi.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Planifier un point mensuel avec la direction.\n"
                        "- Mettre à jour l’avancement.\n"
                        "- Ajuster les actions si besoin.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Objectif : +20% CA perruques.\n"
                        "- Action : campagne WhatsApp + bundle entretien.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Plan d'actions 90 jours",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Plan d'actions 90 jours\n\n"
                        "## À maîtriser absolument\n"
                        "- Structure d’un plan 90 jours.\n"
                        "- Importance du suivi mensuel.\n"
                        "- Livrable : plan 90 jours complet.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q3** : définition et objectifs.\n"
                        "- **Q4–Q6** : construction des actions.\n"
                        "- **Q7–Q10** : erreurs à éviter.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Construire un plan 90 jours avec KPIs.\n"
                    ),
                },
            ],
        },
        {
            "lesson_title": "Évaluation finale",
            "supports": [
                {
                    "title": "Fiche de synthèse – Évaluation finale",
                    "support_type": "SYNTHESIS",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Fiche de synthèse – Évaluation finale\n\n"
                        "## Concepts clés à retenir\n"
                        "- L’évaluation finale valide l’autonomie du manager.\n"
                        "- Elle combine auto-évaluation + feedback direction.\n"
                        "- Le livrable final sert de base pour le plan d’amélioration.\n\n"
                        "## Définitions simples\n"
                        "- **Auto-évaluation** : bilan honnête des compétences.\n"
                        "- **Feedback direction** : retour stratégique de la direction.\n"
                        "- **Plan d’amélioration** : actions pour progresser après la formation.\n\n"
                        "## Règles importantes\n"
                        "- Être factuel et basé sur des preuves.\n"
                        "- Identifier 3 forces + 3 axes d’amélioration.\n"
                        "- Partager la synthèse avec la direction.\n\n"
                        "## Erreurs à éviter\n"
                        "- Surévaluer sans preuves.\n"
                        "- Ignorer les retours direction.\n"
                        "- Ne pas proposer d’actions concrètes.\n"
                    ),
                },
                {
                    "title": "Guide pratique – Évaluation finale",
                    "support_type": "PRACTICAL_GUIDE",
                    "is_mandatory": False,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide pratique – Évaluation finale\n\n"
                        "## Application concrète au salon\n"
                        "1. Réunir les KPI, reportings et actions des 6 semaines.\n"
                        "2. Remplir l’auto-évaluation avec preuves.\n"
                        "3. Préparer un échange avec la direction.\n"
                        "4. Construire un plan d’amélioration 90 jours.\n\n"
                        "## Étapes opérationnelles\n"
                        "- Mettre en avant 3 réussites mesurables.\n"
                        "- Identifier 3 points à renforcer.\n"
                        "- Valider le plan avec la direction.\n\n"
                        "## Exemples Floxy Made\n"
                        "- Réduction des réclamations de 30%.\n"
                        "- Hausse de conversion WhatsApp.\n"
                    ),
                },
                {
                    "title": "Guide de révision – Évaluation finale",
                    "support_type": "REVISION",
                    "is_mandatory": True,
                    "recommended_before_quiz": True,
                    "content_md": (
                        "# Guide de révision – Évaluation finale\n\n"
                        "## À maîtriser absolument\n"
                        "- Structure de l’auto-évaluation.\n"
                        "- Rôle du feedback direction.\n"
                        "- Livrable : score + commentaires finaux.\n\n"
                        "## Liens avec le quiz\n"
                        "- **Q1–Q4** : objectifs et méthodes d’évaluation.\n"
                        "- **Q5–Q7** : preuves et indicateurs.\n"
                        "- **Q8–Q10** : erreurs fréquentes.\n\n"
                        "## Liens avec le mini-cas\n"
                        "- Proposer un plan d’amélioration réaliste.\n"
                    ),
                },
            ],
        },
    ]

    for item in materials:
        lesson = (
            TrainingLesson.objects.filter(title=item["lesson_title"])
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        for support in item["supports"]:
            TrainingStudyMaterial.objects.update_or_create(
                lesson=lesson,
                title=support["title"],
                defaults={
                    "support_type": support["support_type"],
                    "content_md": support["content_md"],
                    "is_mandatory": support["is_mandatory"],
                    "recommended_before_quiz": support["recommended_before_quiz"],
                },
            )


def unseed_week6_study_materials(apps, schema_editor):
    TrainingStudyMaterial = apps.get_model("training", "TrainingStudyMaterial")
    TrainingStudyMaterial.objects.filter(
        title__in=[
            "Fiche de synthèse – Lecture et analyse des KPI",
            "Guide pratique – Lecture et analyse des KPI",
            "Guide de révision – Lecture et analyse des KPI",
            "Fiche de synthèse – Reporting hebdomadaire",
            "Guide pratique – Reporting hebdomadaire",
            "Guide de révision – Reporting hebdomadaire",
            "Fiche de synthèse – Tableau de bord global",
            "Guide pratique – Tableau de bord global",
            "Guide de révision – Tableau de bord global",
            "Fiche de synthèse – Plan d'actions 90 jours",
            "Guide pratique – Plan d'actions 90 jours",
            "Guide de révision – Plan d'actions 90 jours",
            "Fiche de synthèse – Évaluation finale",
            "Guide pratique – Évaluation finale",
            "Guide de révision – Évaluation finale",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0011_seed_week5_study_materials"),
    ]

    operations = [
        migrations.RunPython(seed_week6_study_materials, unseed_week6_study_materials),
    ]
