# Generated by Django 4.2.15 on 2026-01-20 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0012_seed_week6_study_materials"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingConceptCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=120, verbose_name="Terme")),
                (
                    "definition_md",
                    models.TextField(verbose_name="Définition (Markdown)"),
                ),
                (
                    "floxy_example_md",
                    models.TextField(
                        blank=True, verbose_name="Exemple Floxy Made (Markdown)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_cards",
                        to="training.traininglesson",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carte concept",
                "verbose_name_plural": "Cartes concepts",
                "ordering": ["lesson", "term", "id"],
                "unique_together": {("lesson", "term")},
            },
        ),
    ]
