# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_concept_cards(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingConceptCard = apps.get_model("training", "TrainingConceptCard")

    cards = [
        # Week 1
        ("Cartographie des services Floxy Made", "Service phare",
         "Service le plus demandé ou le plus rentable d’un secteur.",
         "Ex: lissage brésilien en coiffure."),
        ("Cartographie des services Floxy Made", "Valeur client",
         "Bénéfice perçu par la cliente (résultat, confort, gain de temps).",
         "Ex: perruque naturelle = confiance + look immédiat."),
        ("Parcours client standardisé", "Diagnostic",
         "Questions rapides pour comprendre besoin, budget, délai et résultat attendu.",
         "Ex: type de perruque souhaitée + usage quotidien ou événement."),
        ("Parcours client standardisé", "Suivi post-prestation",
         "Message envoyé après la prestation pour fidéliser et relancer.",
         "Ex: WhatsApp J+1 pour vérifier la satisfaction."),
        # Week 2
        ("CRM : fiches clientes et segmentation", "CRM",
         "Outil qui centralise les fiches clientes et l’historique.",
         "Ex: noter les services préférés et dates de visites."),
        ("CRM : fiches clientes et segmentation", "Segmentation",
         "Classement des clientes par profil pour mieux relancer.",
         "Ex: VIP, régulières, dormantes."),
        ("Suivi post-prestation J+1/J+7/J+21", "Relance",
         "Message ciblé envoyé pour rester en contact et proposer un RDV.",
         "Ex: relance J+21 pour proposer un entretien perruque."),
        ("Programme fidélité & parrainage", "Parrainage",
         "Cliente existante qui recommande Floxy Made à une nouvelle.",
         "Ex: 1 parrainage validé = soin offert."),
        ("WhatsApp stratégique", "Étiquette WhatsApp",
         "Catégorie pour classer les conversations dans WhatsApp Business.",
         "Ex: “Dormante”, “VIP”, “À relancer”."),
        # Week 3
        ("Identité et ligne éditoriale", "Ligne éditoriale",
         "Règles de communication : ton, messages, visuels.",
         "Ex: style premium, élégant, rassurant."),
        ("Piliers de contenu : transformation, éducation, preuve", "Piliers de contenu",
         "3 types de contenus à équilibrer : transformation, éducation, preuve.",
         "Ex: avant/après, conseils, avis clients."),
        ("Création de vidéos courtes (Reels, TikTok)", "Hook",
         "Accroche des 3 premières secondes d’une vidéo.",
         "Ex: “Regardez la transformation en 20 secondes.”"),
        ("Captions orientées conversion", "CTA",
         "Appel à l’action clair dans un post.",
         "Ex: “Réservez sur WhatsApp maintenant.”"),
        # Week 4
        ("Optimisation des profils sociaux", "Bio",
         "Texte court qui explique clairement l’offre et l’action attendue.",
         "Ex: “Coiffure, perruques, make-up. RDV WhatsApp.”"),
        ("Stratégies de croissance locale", "Géolocalisation",
         "Taguer le lieu pour toucher les clientes proches.",
         "Ex: Abidjan, Cocody, Yopougon."),
        ("Gestion des DM & prise de rendez-vous", "Qualification",
         "Questions pour comprendre le besoin avant de proposer une offre.",
         "Ex: type de service + budget + délai."),
        # Week 5
        ("Offres packagées & bundles", "Bundle",
         "Offre combinée de plusieurs services pour augmenter le panier moyen.",
         "Ex: coiffure + soin profond."),
        ("Upsell & cross-sell", "Upsell",
         "Proposer une version supérieure du service.",
         "Ex: soin premium au lieu du soin basique."),
        ("Upsell & cross-sell", "Cross-sell",
         "Proposer un service complémentaire lié.",
         "Ex: ajouter un kit entretien perruque."),
        ("Objectifs hebdomadaires & suivi CA", "CA",
         "Chiffre d’affaires réalisé sur une période donnée.",
         "Ex: 200k CFA de CA coiffure sur la semaine."),
        ("Management des prestataires", "Brief quotidien",
         "Réunion rapide pour aligner l’équipe sur les objectifs.",
         "Ex: briefing 10 minutes avant ouverture."),
        # Week 6
        ("Lecture et analyse des KPI", "KPI",
         "Indicateur clé pour mesurer la performance.",
         "Ex: taux de retour client, panier moyen."),
        ("Reporting hebdomadaire", "Reporting",
         "Résumé d’une semaine : chiffres + actions.",
         "Ex: 1 page envoyée chaque lundi."),
        ("Tableau de bord global", "Dashboard",
         "Tableau visuel qui regroupe les KPI principaux.",
         "Ex: vue CRM + ventes + marketing."),
        ("Plan d'actions 90 jours", "Plan 90 jours",
         "Feuille de route trimestrielle avec objectifs et actions.",
         "Ex: 3 objectifs majeurs + 5 actions prioritaires."),
    ]

    for lesson_title, term, definition, example in cards:
        lesson = (
            TrainingLesson.objects.filter(title=lesson_title)
            .order_by("id")
            .first()
        )
        if not lesson:
            continue
        TrainingConceptCard.objects.update_or_create(
            lesson=lesson,
            term=term,
            defaults={
                "definition_md": definition,
                "floxy_example_md": example,
            },
        )


def unseed_concept_cards(apps, schema_editor):
    TrainingConceptCard = apps.get_model("training", "TrainingConceptCard")
    terms = [
        "Service phare",
        "Valeur client",
        "Diagnostic",
        "Suivi post-prestation",
        "CRM",
        "Segmentation",
        "Relance",
        "Parrainage",
        "Étiquette WhatsApp",
        "Ligne éditoriale",
        "Piliers de contenu",
        "Hook",
        "CTA",
        "Bio",
        "Géolocalisation",
        "Qualification",
        "Bundle",
        "Upsell",
        "Cross-sell",
        "CA",
        "Brief quotidien",
        "KPI",
        "Reporting",
        "Dashboard",
        "Plan 90 jours",
    ]
    TrainingConceptCard.objects.filter(term__in=terms).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0013_trainingconceptcard"),
    ]

    operations = [
        migrations.RunPython(seed_concept_cards, unseed_concept_cards),
    ]
