# Generated by Django 4.2.15 on 2026-01-20

from django.db import migrations


def seed_sector_concept_cards(apps, schema_editor):
    TrainingLesson = apps.get_model("training", "TrainingLesson")
    TrainingConceptCard = apps.get_model("training", "TrainingConceptCard")

    lesson = (
        TrainingLesson.objects.filter(title="Cartographie des services Floxy Made")
        .order_by("id")
        .first()
    )
    if not lesson:
        return

    cards = [
        ("Coiffure – Lissage brésilien",
         "Traitement qui discipline et détend le cheveu pour un effet lisse durable.",
         "Ex: lissage + soin profond vendu en pack."),
        ("Coiffure – Brushing",
         "Mise en forme temporaire avec chaleur pour donner volume et finition.",
         "Ex: brushing offert après une coloration."),
        ("Perruques – Lace frontal",
         "Perruque avec tulle frontal pour un rendu naturel au niveau de la racine.",
         "Ex: pose lace frontal + conseil entretien."),
        ("Perruques – Closure",
         "Perruque avec fermeture partielle, plus simple et rapide à poser.",
         "Ex: pose closure express pour clientes pressées."),
        ("Make-up – Teint",
         "Base du maquillage : unifier la peau et corriger les imperfections.",
         "Ex: fixation du teint pour maquillage événement."),
        ("Make-up – Fixateur",
         "Produit qui prolonge la tenue du maquillage.",
         "Ex: fixateur offert dans un pack mariage."),
        ("Onglerie – Gel",
         "Technique de renforcement et d’extension des ongles.",
         "Ex: pose gel + nail art simple."),
        ("Onglerie – Semi-permanent",
         "Vernis longue tenue (2–3 semaines).",
         "Ex: semi-permanent express pour clientes actives."),
        ("Soins – Soin visage",
         "Prestation de nettoyage, hydratation et éclat du visage.",
         "Ex: soin visage + diagnostic peau."),
        ("Soins – Gommage",
         "Exfoliation pour enlever les impuretés et lisser la peau.",
         "Ex: gommage corps avant soin hydratant."),
    ]

    for term, definition, example in cards:
        TrainingConceptCard.objects.update_or_create(
            lesson=lesson,
            term=term,
            defaults={
                "definition_md": definition,
                "floxy_example_md": example,
            },
        )


def unseed_sector_concept_cards(apps, schema_editor):
    TrainingConceptCard = apps.get_model("training", "TrainingConceptCard")
    terms = [
        "Coiffure – Lissage brésilien",
        "Coiffure – Brushing",
        "Perruques – Lace frontal",
        "Perruques – Closure",
        "Make-up – Teint",
        "Make-up – Fixateur",
        "Onglerie – Gel",
        "Onglerie – Semi-permanent",
        "Soins – Soin visage",
        "Soins – Gommage",
    ]
    TrainingConceptCard.objects.filter(term__in=terms).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0014_seed_concept_cards"),
    ]

    operations = [
        migrations.RunPython(seed_sector_concept_cards, unseed_sector_concept_cards),
    ]
