# Generated by Django 4.2.15 on 2026-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0015_seed_sector_concept_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingquestion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
    ]
